### ISSUE TITLE
Product and cart links not working - "searching for product"

### ISSUE THREAD

**Issue by knguyenphu** [BazzaAIO/BazzaAIO#4]
many of the tasks are hard stuck on "searching for product" even when given a product link. Please update product links and also cart links for the shopify module. I am also experiencing a lot of issues on supreme test tasks like using keywords "+boxers". I don't think supreme should be a priority at all, but just something to keep in mind. 

ex links

cart link  - https://kith.com/cart/19439269707904:1

product link -  https://kith.com/products/cn170552c

suggestions - 

- Individual captcha harvester page where multiple harvesters and emails can be used and the ability to customize each harvester (checkpoint, checkout) for shopify.
- Adding different shopify modes (fast, preload, safe)
- Importing/exporting profiles function (send aycd jake your import format and he'll add it).

Great job on the project so far!

**Comment by Aries-Spring** [comment]
Keyword related bugs are fixed in recent updates; as for remaining features like improved captcha harvesters, more modes & import/export; those are planned for later updates once stability related issues are all fixed and tested
