### ISSUE TITLE
Custom Sites

### ISSUE THREAD

**Issue by MannyB8** [BazzaAIO/BazzaAIO#5]
When running Custom shopify site it gives you a connection error to the site.

**Comment by Aries-Spring** [comment]
Which website were you using?

Provide a screenshot of task info

**Comment by MannyB8** [comment]
https://odysseyaio.myshopify.com/products/jordan-1-satin-snake-skin 
^ this is my personal shopify site https is not in the task when used cause it says to take it off
![image](https://user-images.githubusercontent.com/66027083/104212077-6e285b00-53fa-11eb-80a7-31fb33f064e1.png)

**Comment by Aries-Spring** [comment]
That's the issue, in Custom URL field, you're supposed to provide the main url for the website which in your case would be:

`odysseyaio.myshopify.com`
